# Generated by Django 4.2.20 on 2025-03-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kelly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_pending',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='kelly.submission'),
        ),
    ]
