# Generated by Django 4.2.20 on 2025-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelly', '0002_remove_feedback_is_pending_alter_feedback_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='remarks',
            field=models.CharField(choices=[('5', '5 - Excellent'), ('4', '4 - Very Good'), ('3', '3 - Good'), ('2', '2 - Average'), ('1', '1 - Poor')], default='5', max_length=2),
        ),
    ]
